Update docker.md registry_url examples
The registry_url value in this document does not work.  I got the following error:

```
Successfully built dbe32999e1ce
Successfully tagged k24d/myflow:2020-09-17t22-55-39-290448-00-00
Traceback (most recent call last):
...
ValueError: Your docker image failed to build!  Your flow might have failed one of its deployment health checks - please ensure that all necessary files and dependencies have been included.
```

This is because Docker doesn't set the prefix "docker.io/" for Docker Hub images.